project:
  type: website
  output-dir: docs

website:
  title: "Brian Bieza Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Portfolio_Project/Stat_210_Final_Project.qmd
        text: Final Project

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
